#!/bin/bash

depmod -a 4.14.87

config_file="/lib/modules-load.d/10-hobot_modules.conf"

if [ ! -f "/sys/class/socinfo/soc_uid" ]; then
    exit 0
fi

# for modname in `cat ${config_file}`
while read modname
do
    if [ -n "$modname" ];then
        # echo -e "#mod=${modname#*#} mod=${modname}"
        if [ x"${modname#*#}" == x"${modname}" ];then
            modprobe $modname
            if [ $? != 0 ];then
                echo "modlue: [ $modname ] install failed"!
            fi
        fi
    else
        echo "modlue: [ $modname ] is not exist"!
    fi
done < ${config_file}

exit 0

